language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - pecl install xmldiff
  - echo "xdebug.max_nesting_level=1000" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
before_script:
  - if [[ $TRAVIS_PHP_VERSION = '5.6' ]]; then PHPUNIT_FLAGS="--coverage-clover=coverage.clover"; else PHPUNIT_FLAGS=""; fi
  - if [[ $TRAVIS_PHP_VERSION != '5.6' ]]; then phpenv config-rm xdebug.ini; fi  
  - composer install --prefer-dist --dev

script: vendor/phpunit/phpunit/phpunit $PHPUNIT_FLAGS

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - if [[ $TRAVIS_PHP_VERSION = '5.6' && $DB = 'sqlite' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover fi
  
