language: php

php:
  - 5.4
  - 5.5
#  - hhvm

before_script:
  - composer install --prefer-dist --dev

script: vendor/phpunit/phpunit/phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
